---
title: "GHG Emmisions"
author: "Monae Scott"
date: '2022-06-10'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = F)
options(scipen = 999)
```
```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(ggthemes)
# Greenhouse gas emissions by country-year, 1750 - 2020
ghg <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2.csv')

# Greenhouse gas emissions by country-year-sector, 1990 - 2018
sectors <- read_csv('https://raw.githubusercontent.com/ericmkeen/capstone/master/co2_sectors.csv')
```

```{r}
#who is emitting the most each sector 
sectors_filtered<-sectors %>% 
  group_by(entity,year) %>% 
  summarise(total=sum(co2)/100000000) %>%
  ungroup()

df<-sectors_filtered %>% 
  group_by(year) %>% 
  filter( ! entity %in% c("World", "European Union (27)" )) %>%
  slice_max(order_by = total, n=5) 

ggplot(data = df, aes(x=year, y=total))+
  geom_line()+
  geom_area(fill="darkblue", alpha=0.5)+
  labs(title = "Top 5 CO2 Emitters", x="Total Number of CO2 Emission (Millions)", y="Country")+
  facet_wrap(~entity,scales = "free")+
  theme_clean()
    
df.2<-sectors %>% 
  group_by(sector, entity) %>%
  summarise(total=sum(co2)/100000000) %>% 
  ungroup()
  
 sec<-df.2 %>% 
   group_by(sector) %>%
    filter( ! entity %in% c("World", "European Union (27)" ))%>%
   slice_max(order_by = total, n=5) 
 
   
 ggplot(data = sec, aes(x=entity, y=total, fill=entity))+
  geom_col()+
  labs(title = "Top 5 CO2 Emitters by Sector",y="Total Number of CO2 Emission (Millions)", x="Country")+
  facet_wrap(~sector,scales = "free", labeller = labeller(sector = label_wrap_gen(20)))+
  coord_flip()+
  theme_clean()+
  theme(legend.position = "none")
              
```